'use strict';
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={page:'overview',nodes:[],rules:[],events:[],revision:0,retention_days:30,search:'',group:'',nodeFilter:'',pageNum:1,probes:{},user:''};
const titles={overview:'总览',nodes:'服务器',rules:'转发规则',diagnostic:'连通诊断',events:'操作记录',settings:'设置'};
async function api(path,method='GET',data){const options={method,headers:{'X-Nexus-Request':'panel'}};if(data!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(data)}const response=await fetch('/api'+path,options);let body;try{body=await response.json()}catch{throw new Error('服务器响应无效')}if(!response.ok)throw new Error(body.error||`请求失败 (${response.status})`);return body}
let toastTimer;function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),3200)}
function showLogin(){ $('#app').classList.add('hidden');$('#login').classList.remove('hidden') }
function showApp(){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden') }
async function load(silent=false){try{const data=await api('/dashboard');Object.assign(state,data);$('#sync-time').textContent='更新于 '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(!silent||!['INPUT','SELECT'].includes(document.activeElement.tagName)&&$('#modal').classList.contains('hidden'))render()}catch(e){if(!silent)toast(e.message,true);if(e.message.includes('登录'))showLogin()}}
function nodeName(id){return state.nodes.find(n=>n.id===id)?.name||'已删除服务器'}
function online(n){return Date.now()/1000-n.last_seen<20}
function nodeStatus(n){return !online(n)?'<span class="status failed">离线</span>':n.error?'<span class="status warning">异常</span>':n.applied_revision===state.revision?'<span class="status online">运行中</span>':'<span class="status warning">下发中</span>'}
function metric(title,value,sub,color){return `<div class="metric"><span>${title}</span><strong>${value}</strong><small>${sub}</small></div>`}
function intro(text,button=''){return `<div class="intro"><p>${text}</p>${button}</div>`}
function panel(title,body,sub=''){return `<section class="panel"><header class="panel-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div></header>${body}</section>`}
function empty(title,subtitle){return `<div class="empty"><strong>${title}</strong>${subtitle}</div>`}
function overview(){const active=state.nodes.filter(online).length;const enabled=state.rules.filter(r=>r.enabled).length;const problematic=state.nodes.filter(n=>n.error).length;let body=intro('所有服务器与转发规则集中管理，状态每 10 秒自动更新。',`<button class="primary" data-action="new-rule">＋ 创建规则</button>`);body+=`<div class="metrics">${metric('服务器',state.nodes.length,`${active} 台在线`,'#4f6ef7')}${metric('转发规则',state.rules.length,`${enabled} 条已启用`,'#159f70')}${metric('待处理异常',problematic,'节点上报的运行错误','#d84d61')}${metric('转发引擎','Realm','TCP / UDP','#bc7a12')}</div>`;const recentNodes=state.nodes.slice(0,6).map(n=>`<div class="line-item"><div><strong>${esc(n.name)}</strong><small>${esc(n.address||'未填写地址')} · ${esc(n.grp||'未分组')}</small></div>${nodeStatus(n)}</div>`).join('')||empty('还没有服务器','先添加服务器，再在服务器上安装代理。');const recentEvents=state.events.slice(0,6).map(e=>`<div class="line-item"><div><strong>${esc(e.action)}</strong><small>${esc(e.detail)} · ${esc(e.actor)}</small></div><span class="event-date">${date(e.created_at)}</span></div>`).join('')||empty('暂无操作记录','创建第一台服务器即可开始。');body+=`<div class="split">${panel('服务器状态',`<div class="panel-body">${recentNodes}</div>`,'最近连接的服务器')}${panel('最近操作',`<div class="panel-body">${recentEvents}</div>`,'保留期可在设置中调整')}</div>`;return body}
function date(ts){return ts?new Date(ts*1000).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
function filtered(items){const q=state.search.toLowerCase();return items.filter(item=>{if(state.group&&item.grp!==state.group)return false;if(state.nodeFilter&&String(item.node_id)!==state.nodeFilter)return false;return !q||[item.name,item.address,item.grp,item.remote_host,item.extra_remotes,item.listen_port,item.remote_port,nodeName(item.node_id)].some(x=>String(x??'').toLowerCase().includes(q))})}
function paging(items){const count=Math.max(1,Math.ceil(items.length/30));state.pageNum=Math.min(state.pageNum,count);const slice=items.slice((state.pageNum-1)*30,state.pageNum*30);return {slice,footer:`<div class="pager"><span>共 ${items.length} 条 · 第 ${state.pageNum}/${count} 页</span><button data-action="prev" ${state.pageNum===1?'disabled':''}>上一页</button><button data-action="next" ${state.pageNum===count?'disabled':''}>下一页</button></div>`}}
function toolbar(kind){const items=kind==='nodes'?state.nodes:state.rules;const groups=[...new Set(items.map(x=>x.grp).filter(Boolean))].sort();return `<div class="toolbar"><input id="search" aria-label="搜索" placeholder="搜索名称、地址或端口" value="${esc(state.search)}"><select id="group-filter" aria-label="分组"><option value="">全部分组</option>${groups.map(x=>`<option value="${esc(x)}" ${x===state.group?'selected':''}>${esc(x)}</option>`).join('')}</select>${kind==='rules'?`<select id="node-filter" aria-label="服务器"><option value="">全部服务器</option>${state.nodes.map(n=>`<option value="${n.id}" ${String(n.id)===state.nodeFilter?'selected':''}>${esc(n.name)}</option>`).join('')}</select>`:''}<span class="spacer"></span><button class="primary" data-action="new-${kind==='nodes'?'node':'rule'}">＋ 添加${kind==='nodes'?'服务器':'规则'}</button></div>`}
function nodes(){let out=intro('统一管理转发服务器，添加后复制一次性密钥到目标服务器安装代理。');const {slice,footer}=paging(filtered(state.nodes));const rows=slice.map(n=>`<tr><td><strong>${esc(n.name)}</strong><small>${esc(n.grp||'未分组')}</small></td><td class="mono">${esc(n.address||'—')}</td><td>${nodeStatus(n)}${n.error?`<small title="${esc(n.error)}">${esc(n.error.slice(0,55))}</small>`:''}</td><td>${n.last_seen?date(n.last_seen):'从未连接'}</td><td class="actions"><button data-action="edit-node" data-id="${n.id}">编辑</button><button data-action="reset-token" data-id="${n.id}">密钥</button><button class="danger" data-action="delete-node" data-id="${n.id}">删除</button></td></tr>`).join('');out+=`<section class="panel">${toolbar('nodes')}<div class="table-wrap"><table class="data-table"><thead><tr><th>服务器 / 分组</th><th>连接地址</th><th>状态</th><th>最后心跳</th><th style="text-align:right">操作</th></tr></thead><tbody>${rows||`<tr><td colspan="5">${empty('没有匹配的服务器','可调整搜索或添加服务器。')}</td></tr>`}</tbody></table></div>${footer}</section>`;return out}
function rules(){let out=intro('按服务器和分组快速定位规则。保存后节点通常会在约 10 秒内拉取并应用。');const {slice,footer}=paging(filtered(state.rules));const rows=slice.map(r=>`<tr><td><strong>${esc(r.name)}</strong><small>${esc(r.grp||'未分组')}</small></td><td>${esc(nodeName(r.node_id))}</td><td class="mono">${esc(r.listen_host)}:${r.listen_port}</td><td class="mono">${esc(r.remote_host)}:${r.remote_port}${r.extra_remotes?.length?` <span class="tag" title="${esc(r.extra_remotes.join(", "))}">＋${r.extra_remotes.length} 出口</span>`:""}</td><td><span class="tag">${esc(r.protocol.toUpperCase())}</span></td><td><span class="status ${r.enabled?'online':''}">${r.enabled?'已启用':'已停用'}</span></td><td class="actions"><button data-action="toggle-rule" data-id="${r.id}">${r.enabled?'停用':'启用'}</button><button data-action="edit-rule" data-id="${r.id}">编辑</button><button class="danger" data-action="delete-rule" data-id="${r.id}">删除</button></td></tr>`).join('');out+=`<section class="panel">${toolbar('rules')}<div class="table-wrap"><table class="data-table"><thead><tr><th>规则 / 分组</th><th>服务器</th><th>监听地址</th><th>目标地址</th><th>协议</th><th>状态</th><th style="text-align:right">操作</th></tr></thead><tbody>${rows||`<tr><td colspan="7">${empty('没有匹配的规则','添加规则后，节点代理会自动下发到 Realm。')}</td></tr>`}</tbody></table></div>${footer}</section>`;return out}
function diagnostic(){const rows=state.rules.filter(r=>r.enabled).map(r=>{const p=state.probes[r.id];const status=p===undefined?'—':p===null?'测试中…':p.reachable?`<span class="latency ${p.ms<130?'good':'slow'}">${p.ms} ms</span>`:'<span class="latency bad">不可达</span>';return `<tr><td><strong>${esc(r.name)}</strong><small>${esc(nodeName(r.node_id))}</small></td><td class="mono">${esc(r.remote_host)}:${r.remote_port}</td><td>${status}</td><td class="actions"><button data-action="probe-rule" data-id="${r.id}" ${r.protocol==='udp'?'disabled title="TCP 探测不适用于 UDP"':''}>测试</button></td></tr>`}).join('');return intro('TCP 测试从面板服务器发起，耗时直接显示在行内；UDP 无法通过此方法判断。')+`<div class="panel"><div class="toolbar"><strong>目标连通性</strong><span class="spacer"></span><button data-action="probe-all">测试全部 TCP</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>规则</th><th>目标</th><th>延迟</th><th style="text-align:right">操作</th></tr></thead><tbody>${rows||`<tr><td colspan="4">${empty('暂无启用的规则','添加转发规则后在这里检查目标端口。')}</td></tr>`}</tbody></table></div></div><p class="footnote">这里显示面板 → 目标的 TCP 建连时间，不等于用户 → 中转 → 目标的完整链路延迟；绿色 &lt;130 ms，黄色 ≥130 ms。</p>`}
function events(){return intro('记录管理员的配置变更，默认保留 30 天。')+panel('操作记录',`<div class="table-wrap"><table class="data-table"><thead><tr><th>操作</th><th>详情</th><th>账号</th><th>时间</th></tr></thead><tbody>${state.events.map(e=>`<tr><td><strong>${esc(e.action)}</strong></td><td>${esc(e.detail)}</td><td>${esc(e.actor)}</td><td>${date(e.created_at)}</td></tr>`).join('')||`<tr><td colspan="4">${empty('暂无记录','配置变更会显示在这里。')}</td></tr>`}</tbody></table></div>`) }
function settings(){return intro('管理员账号、审计记录与安装操作。')+`<div class="settings-grid">${panel('修改密码',`<form id="password-form" class="panel-body"><label>当前密码<input name="current" type="password" required></label><label>新密码（至少 12 位）<input name="password" type="password" minlength="12" required></label><button class="primary">保存密码</button></form>`)}${panel('修改账号',`<form id="username-form" class="panel-body"><label>新账号名<input name="username" value="${esc(state.user)}" minlength="3" maxlength="32" required></label><label>当前密码<input name="password" type="password" required></label><button class="primary">保存账号</button></form>`)}${panel('记录保留',`<form id="retention-form" class="panel-body"><p class="muted small">操作记录自动清理；登录会话到期后自动删除。数据库备份与恢复在 SSH 菜单中操作。</p><label>保留天数（1–365）<input name="retention_days" type="number" min="1" max="365" value="${state.retention_days}" required></label><button class="primary">保存设置</button></form>`)}${panel('SSH 管理菜单',`<div class="panel-body"><p class="muted small">在面板服务器的 SSH 终端运行：</p><code class="secret">sudo nexus-panel</code><p class="footnote">可检查服务、更新、修改域名、重置密码、备份与恢复。安装脚本支持 Debian / Ubuntu。</p></div>`)}</div>`}
function render(){const page=state.page;$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#title').textContent=titles[page];$('#breadcrumb').textContent='WORKSPACE / '+page.toUpperCase();$('#content').innerHTML=({overview,nodes,rules,diagnostic,events,settings})[page]();$('#username').textContent=state.user||'管理员'}
function modal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal').classList.remove('hidden');setTimeout(()=>$('#modal input')?.focus(),0)}function closeModal(){$('#modal').classList.add('hidden');$('#modal-body').innerHTML=''}
function nodeForm(n){modal(n?'编辑服务器':'添加服务器',`<form id="node-form" data-id="${n?.id||''}" class="form-grid"><label>服务器名称<input name="name" maxlength="80" value="${esc(n?.name||'')}" required></label><label>分组（可选）<input name="grp" maxlength="60" value="${esc(n?.grp||'')}"></label><label class="wide">连接地址（展示用，IP 或域名）<input name="address" value="${esc(n?.address||'')}" placeholder="例如 relay.example.com"></label><div class="hint wide">创建后会生成一次性展示的节点密钥。请在这台服务器运行代理安装命令。</div><div class="form-actions wide"><button type="button" data-close="1">取消</button><button class="primary">${n?'保存修改':'创建服务器'}</button></div></form>`)}
function ruleForm(r){if(!state.nodes.length)return toast('请先添加服务器',true);modal(r?'编辑规则':'创建转发规则',`<form id="rule-form" data-id="${r?.id||''}" class="form-grid"><label>规则名称<input name="name" value="${esc(r?.name||'')}" maxlength="80" required></label><label>所属服务器<select name="node_id" ${r?'disabled':''}>${state.nodes.map(n=>`<option value="${n.id}" ${r?.node_id===n.id?'selected':''}>${esc(n.name)}</option>`).join('')}</select></label><label>分组（可选）<input name="grp" maxlength="60" value="${esc(r?.grp||'')}"></label><label>协议<select name="protocol">${['tcp','udp','both'].map(p=>`<option value="${p}" ${(r?.protocol||'tcp')===p?'selected':''}>${p.toUpperCase()}</option>`).join('')}</select></label><label>监听 IP<input name="listen_host" value="${esc(r?.listen_host||'0.0.0.0')}" required></label><label>监听端口<input name="listen_port" type="number" min="1" max="65535" value="${r?.listen_port||''}" required></label><label>目标域名或 IP<input name="remote_host" value="${esc(r?.remote_host||'')}" placeholder="example.com" required></label><label>目标端口<input name="remote_port" type="number" min="1" max="65535" value="${r?.remote_port||''}" required></label><label class="wide">附加目标（可选，每行一个 域名:端口）<textarea name="extra_remotes" rows="3" placeholder="backup.example.com:443">${esc((r?.extra_remotes||[]).join("\n"))}</textarea></label><label class="wide">分配策略<select name="balance"><option value="off" ${(r?.balance||"off")==="off"?"selected":""}>单一目标</option><option value="roundrobin" ${r?.balance==="roundrobin"?"selected":""}>轮询</option><option value="iphash" ${r?.balance==="iphash"?"selected":""}>IP 哈希</option></select></label><label class="wide"><input name="enabled" type="checkbox" class="check-input" ${!r||r.enabled?'checked':''}>启用此规则</label><div class="form-actions wide"><button type="button" data-close="1">取消</button><button class="primary">保存规则</button></div></form>`)}
function tokenModal(token){modal('节点安装',`<div class="stack"><p class="hint">密钥只展示这一次。请复制并妥善保存；重置密钥会使旧代理断开。</p><label>节点密钥<code class="secret">${esc(token)}</code></label><p class="muted small">在目标服务器的 SSH 中运行：</p><code class="secret">curl -fsSL https://raw.githubusercontent.com/a2899882/Nexus-panel/main/scripts/install-agent.sh -o /tmp/nexus-agent-install.sh &amp;&amp; sudo bash /tmp/nexus-agent-install.sh</code><p class="footnote">脚本会交互式询问面板 HTTPS 地址和上面的密钥。面板与节点都需要可访问 GitHub。</p><div class="form-actions"><button data-close="1">完成</button></div></div>`)}
function formData(form){return Object.fromEntries(new FormData(form))}
async function withBusy(button,fn){button.disabled=true;try{await fn()}catch(e){toast(e.message,true)}finally{button.disabled=false}}
async function probe(r){state.probes[r.id]=null;render();try{state.probes[r.id]=await api('/probe','POST',{host:r.remote_host,port:r.remote_port});render()}catch(e){delete state.probes[r.id];toast(e.message,true);render()}}
async function action(kind,id){const n=state.nodes.find(x=>x.id===id),r=state.rules.find(x=>x.id===id);if(kind==='new-node')return nodeForm();if(kind==='edit-node')return nodeForm(n);if(kind==='new-rule')return ruleForm();if(kind==='edit-rule')return ruleForm(r);if(kind==='prev'||kind==='next'){state.pageNum+=kind==='next'?1:-1;return render()}if(kind==='probe-rule')return probe(r);if(kind==='probe-all'){const work=state.rules.filter(x=>x.enabled&&x.protocol!=='udp');let cursor=0;await Promise.all(Array.from({length:Math.min(6,work.length)},async()=>{while(cursor<work.length)await probe(work[cursor++])}));return}if(kind==='reset-token'){if(!confirm(`重置「${n.name}」的密钥？旧代理将无法同步新规则，但会继续执行本机已有转发；请及时在节点更新密钥或停用服务。`))return;const result=await api(`/nodes/${id}/token`,'POST',{});tokenModal(result.token);return}if(kind==='delete-node'||kind==='delete-rule'){const item=n||r;if(!confirm(`确定删除「${item.name}」？${n?'其下全部规则也会删除。':''}`))return;await api(`/${n?'nodes':'rules'}/${id}`,'DELETE');toast('已删除');return load()}if(kind==='toggle-rule'){await api(`/rules/${id}`,'PUT',{...r,enabled:!r.enabled});toast(r.enabled?'已停用':'已启用');return load()}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('button',e.target);await withBusy(btn,async()=>{try{const form=formData(e.target);await api('/login','POST',form);state.user=form.username;$('#login-error').textContent='';showApp();await load()}catch(err){$('#login-error').textContent=err.message}})});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;state.page=b.dataset.page;state.search='';state.group='';state.nodeFilter='';state.pageNum=1;render();$('.sidebar').classList.remove('open');$('#scrim').classList.add('hidden')});
$('#mobile-menu').onclick=()=>{$('.sidebar').classList.add('open');$('#scrim').classList.remove('hidden')};$('#scrim').onclick=()=>{$('.sidebar').classList.remove('open');$('#scrim').classList.add('hidden')};$('#refresh').onclick=()=>load();$('#logout').onclick=async()=>{await api('/logout','POST',{});showLogin()};
document.addEventListener('click',async e=>{if(e.target.closest('[data-close]'))return closeModal();const b=e.target.closest('[data-action]');if(!b)return;await withBusy(b,()=>action(b.dataset.action,Number(b.dataset.id)))});
$('#content').addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;state.pageNum=1;const pos=e.target.selectionStart;render();const search=$('#search');search.focus();search.setSelectionRange(pos,pos)}});
$('#content').addEventListener('change',e=>{if(e.target.id==='group-filter'||e.target.id==='node-filter'){state[e.target.id==='group-filter'?'group':'nodeFilter']=e.target.value;state.pageNum=1;render()}});
document.addEventListener('submit',async e=>{if(e.target.id==='login-form')return;e.preventDefault();const f=e.target,button=$('button[type=submit],button.primary',f);await withBusy(button,async()=>{const data=formData(f);
if(f.id==='node-form'){const id=f.dataset.id;const result=await api(id?`/nodes/${id}`:'/nodes',id?'PUT':'POST',data);closeModal();await load();if(!id)tokenModal(result.token);else toast('服务器已更新')}
else if(f.id==='rule-form'){const id=f.dataset.id;const body={...data,enabled:!!f.elements.enabled.checked};if(id)body.node_id=state.rules.find(r=>r.id===Number(id)).node_id;await api(id?`/rules/${id}`:'/rules',id?'PUT':'POST',body);closeModal();toast(id?'规则已更新':'规则已创建');await load()}
else if(f.id==='password-form'){await api('/password','POST',data);toast('密码已更新，请重新登录');showLogin()}
else if(f.id==='username-form'){await api('/username','POST',data);state.user=data.username;toast('账号已更新');render()}
else if(f.id==='retention-form'){await api('/settings','POST',data);toast('设置已保存');await load()}
})});
(async()=>{try{const me=await api('/me');state.user=me.username;showApp();await load()}catch{showLogin()}})();
setInterval(()=>{if(!$('#app').classList.contains('hidden'))load(true)},10000);
